[book]
authors = ["Drocula"]
language = "zh-CN"
multilingual = false
src = "src"
title = "社区讨论存档"

[output.html]
git-repository-url = "https://github.com/dpdk-dev/dpdk-dev.github.io.src"
git-repository-icon = "fa-github"

[output.html.playpen]
editable = true