version: 2.1
jobs:
  build:
    docker: 
      - image: dbuildrobot/mdbook-ci:0.4.7 # the primary container, where your job's commands are run

    steps:
      - checkout # check out the code in the project directory
      - run: mdbook build
      - run: pwd
      - run: cd book
      - run: pwd